[package]
authors = []
name = "todolist"
version = "1.0.0"

[addresses]
todolist_addr = "f1807e33128a31d6f2751ccd6dc46ad30c114f32cfe8a7e97bfa20696f0749b0"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
